#!/bin/sh

if [[ $1 == "build" ]]
then
  watch="false"
else
  watch="true"
fi

echo test 1

writ=../writ-cms/bin.js

node $writ . \
  --watch $watch \
  --test "1"

echo test 2

node $writ . --watch $watch --test "2"

echo test 3

node $writ . --watch $watch --test="3"

echo test 4

node $writ . \
  --watch $watch \
  --test="4"
